### PR TITLE
Missing textdomains

### PR DESCRIPTION
**Pull request by gabormeszoly**
Added translation strings

### CODE REVIEW

**Comment by ThierryA** [comment]
Hi @gabormeszoly,

Thank you very much for your contribution:) I have just added [a Contribute section](https://github.com/gabormeszoly/Beans#community) as it is very important to us to keep the GitHub repo as clean as Beans code!

Could you kindly change the commit descriptions to "Added translation strings..." for example. Also make sure that you don't add a blank tab at the end if the file.

Thanks again buddy,

**Comment by gabormeszoly** [comment]
Hi @ThierryA ,
I resubmit my PR few hours later ...
Thanks, Gabor

**Comment by gabormeszoly** [comment]
@ThierryA btw, what is the correct solution about the "No newline at end of file"?

**Comment by ThierryA** [comment]
Great @gabormeszoly,

Never mind about the new line at the end, we are slowly going to have them at the end of every file since a lot of editor adds it by default.

Thanks,

**Pull request closed without merging**
