### PR TITLE
Improved accessibility of icons

### PR DESCRIPTION
**Pull request by christophherr**
See #99

### CODE REVIEW

**Comment by christophherr** [comment]
I don't mind removing the visible additions although they reduce the cognitive load. 

I would advocate for adding Post, Posts and Comments as screen-reader-text.

You know what "Next" and "Previous" stand for because you see that you are at the end of the Post.
If you don't see that, does it mean there is a previous or next part of the post that you are going to navigate to, does it mean you are going to the next or previous unrelated post?

**Comment by christophherr** [comment]
I like that :)

Is the consensus to keep `post, posts, comments` and use filters to change them?

These are already available:
```[php]
beans_previous_text[_posts_pagination]_output
beans_next_text[_posts_pagination]_output

beans_next_text[_comments_navigation]_output
beans_previous_text[_comments_navigation]_output
``` 

Should the new filters follow that pattern?  
```
beans_post_navigation_item_text_previous_output
beans_post_navigation_item_text_next_output
```
(using `beans_post_navigation_item_text[_previous]_output` needs a `phpcs:ignore`  because it's a "vanilla 
 WP" hook name)

**Comment by hellofromtonya** [comment]
@iCaspar and @christophherr Filters exist already for the Next and Previous Pagination text, i.e. the links on archive pages.

```
add_filter( 'beans_next_text[_posts_pagination]_output', __NAMESPACE__ . '\change_next_pagination_text' );
function change_next_pagination_text() {
	return __( 'Next Foo', 'your-text-domain' );
}

add_filter( 'beans_previous_text[_posts_pagination]_output', __NAMESPACE__ . '\change_previous_pagination_text' );
function change_previous_pagination_text() {
	return __( 'Previous Foo', 'your-text-domain' );
}
```

## Next & Previous Post Links

For the next and previous post links, WordPress has a filter `previous_post_link` and `next_post_link` that gives us the link + text:

```
	/**
	 * Filters the adjacent post link.
	 *
	 * The dynamic portion of the hook name, `$adjacent`, refers to the type
	 * of adjacency, 'next' or 'previous'.
	 *
	 * @since 2.6.0
	 * @since 4.2.0 Added the `$adjacent` parameter.
	 *
	 * @param string  $output   The adjacent post link.
	 * @param string  $format   Link anchor format.
	 * @param string  $link     Link permalink format.
	 * @param WP_Post $post     The adjacent post.
	 * @param string  $adjacent Whether the post is previous or next.
	 */
	return apply_filters( "{$adjacent}_post_link", $output, $format, $link, $post, $adjacent );
``` 

Now, that doesn't give us access to just the text within the link though.  To do that, we'd have to do this:

```
	if ( $previous ) {
		// Previous.
		beans_open_markup_e( 'beans_post_navigation_item[_previous]', 'li', array( 'class' => 'uk-pagination-previous' ) );

			// phpcs:ignore WordPress.XSS.EscapeOutput.OutputNotEscaped -- Echoes HTML output.
			echo get_previous_post_link(
				'%link',
				beans_output( 'beans_previous_text[_post_navigation_item]', __( 'Previous', 'tm-beans' ) )
			);

		beans_close_markup_e( 'beans_post_navigation_item[_previous]', 'li' );
	}

	if ( $next ) {
		// Next.
		beans_open_markup_e( 'beans_post_navigation_item[_next]', 'li', array( 'class' => 'uk-pagination-next' ) );

			// phpcs:ignore WordPress.XSS.EscapeOutput.OutputNotEscaped -- Echoes HTML output.
			echo get_next_post_link(
				'%link',
				beans_output( 'beans_next_text[_post_navigation_item]', __( 'Next', 'tm-beans' ) )
			);

		beans_close_markup_e( 'beans_post_navigation_item[_next]', 'li' );
	}
```

And then theme developers can filter the output like this:

```
add_filter( 'beans_next_text[_post_navigation_item]_output', __NAMESPACE__ . '\change_next_post_navigation_text' );
function change_next_post_navigation_text() {
	return __( 'Next Foo Item', 'your-text-domain' );
}

add_filter( 'beans_previous_text[_post_navigation_item]_output', __NAMESPACE__ . '\change_previous_post_navigation_text' );
function change_previous_post_navigation_text() {
	return __( 'Previous Foo Item', 'your-text-domain' );
}
```

**Comment by hellofromtonya** [comment]
I know you're busy this week, @christophherr. So I thought I'd help you out.  I pushed 2 commits to this PR:

1. Adds a new previous and next text filter per the discussion above.  This change gives theme developers a specific hook for changing the text.
2. Changed the word "Posts" and "Post" to "Page."  This generic word literally means to go to the next or previous web page.  That solves the contextual problem of different types of post types, should the content be a book, listing, FAQ, or whatever.

What you think?

**Comment by christophherr** [comment]
Wonderful 👍 
I like that this adds a filter to one of the few places that were not "filtereable" and describes where the link will go.

**Pull request merged**
