### PR TITLE
Fixing local path

### PR DESCRIPTION
**Pull request by karrirasinmaki**
This pull request will fix local paths given by function beans_url_to_path(string) on some environments.

The problem arose, fixed and tested on this WP Vagrant box (ubuntu/xenial64):
https://github.com/Seravo/wordpress

The tested environment has slightly different file structure than normal WP installation.

### CODE REVIEW

**Comment by christophherr** [comment]
Hey @karrirasinmaki,

thanks for the updated PR.
Can you please target it against development and not master?

This is still breaking our tests.

```[sh]
There were 2 failures:

1) Beans\Framework\Tests\Unit\API\Utilities\Tests_BeansUrlToPath::test_should_bail_out_when_external_url
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-ftp://foo.com
+./ftp:/foo.com

C:\laragon\www\beans\wp-content\themes\Beans\tests\phpunit\unit\api\utilities\beansUrlToPath.php:53

2) Beans\Framework\Tests\Unit\API\Utilities\Tests_BeansUrlToPath::test_should_bail_out_when_external_url_with_internal_pathFailed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-http://example.com/cool-stuff-at-www.getbeans.io
+./http:/example.com/cool-stuff-at-www.getbeans.io

C:\laragon\www\beans\wp-content\themes\Beans\tests\phpunit\unit\api\utilities\beansUrlToPath.php:83
```

**Comment by christophherr** [comment]
Hey @karrirasinmaki,
We are trying a different approach. 
Could you please check if #334 solves the problem for you?

**Comment by karrirasinmaki** [comment]
Hey,

unfortunately this that won't fix the problem. I still got this error message:
```
Warning: include(/wp-content/themes/um-child/index.php): failed to open stream: No such file or directory in /data/wordpress/htdocs/wp-content/themes/um-child/page.php on line 2
```

Based on the discussion on #332 (`beans_url_to_path()` handling this issue no good) I would say let's try to tackle that issue in PR #334.

**Comment by christophherr** [comment]
Hey @karrirasinmaki
I think you have to give us more detail or context on what the problem is and what you are trying to achieve and what you expect Beans to do for you because it looks like all you have to do is to correct the path in your include statement. 
334 is not going to fix that.

**Comment by karrirasinmaki** [comment]
Hey,

I finally got more time to test this issue and PR #334. Seems like that PR solved the problem after all!

**Comment by karrirasinmaki** [comment]
Hey,

I finally got more time to test this issue and PR #334. Seems like that PR solved the problem after all!

**Comment by karrirasinmaki** [comment]
Hey,

I finally got more time to test this issue and PR #334. Seems like that PR solved the problem after all!

**Pull request closed without merging**
